[project]
name = "django-vpn-demo"
version = "0.1.0"
description = "A demo project to show how to use Django partially behind a VPN"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0",
    "django-hosts>=7.0.0",
    "gunicorn>=23.0.0",
    "whitenoise>=6.8.2",
]
